<MainWindow>:
    id: main_win

    ScreenManager:
        id: scrn_mngr_main

        Screen:
            id: scrn_si
            name: 'scrn_si'
        Screen:
            id: scrn_admin
            name: 'scrn_admin'
        Screen:
            id: scrn_op
            name: 'scrn_op'
        Screen:
            id: scrn_map
            name: 'scrn_map' 
        Screen:
            id: scrn_list
            name: 'scrn_list'